**Generate random samples from various distributions**

In [3]:
import numpy as np

In [4]:
np.random.seed(42)

In [5]:
normal_samples = np.random.normal(loc =0,scale=1,size=1000) ## Normal distribution (mean=0, std=1)

In [6]:
uniform_samples = np.random.uniform(low =0.0,high =1.0,size =1000) ## Uniform distribution (low=0, high=1

In [7]:
binomial_samples = np.random.binomial(n=10,p=0.5,size=1000) ## Binomial distribution (n=10, p=0.5)

**b. Create large multidimensional arrays to simulate complex dat**

In [8]:
large_array=np.random.randint(0,100,size=(100,100,100))

Explanation:

np.random.seed(42) ensures that the random numbers are reproducible.
Normal Distribution: Simulates data that follows a bell curve.
Uniform Distribution: Simulates data where every number has an equal chance.
Binomial Distribution: Useful for simulating scenarios with two outcomes (e.g., success/failure).
Large Array: Simulates complex, multidimensional data.


**Master array creation and reshaping.**

General Format: np.arange(start, stop, step)
Key Notes:
Creates an array with evenly spaced values within a specified interval.
start: Starting value of the sequence.
stop: End value of the sequence (exclusive).
step: Spacing between values.


In [20]:
#using arange
array_arange =np.arange(0,10,1)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


General Format: np.linspace(start, stop, num)
Key Notes:
Generates an array of evenly spaced numbers over a specified interval.
start: Starting value of the sequence.
stop: End value of the sequence (inclusive).
num: Number of samples to generate

In [19]:
array_linspace =np.linspace(0,1,5)
print(array_linspace)

[0.   0.25 0.5  0.75 1.  ]


General Format: np.zeros(shape)
Key Notes:
Returns a new array of given shape filled with zeros.
shape: Tuple indicating the dimensions of the array.

In [11]:
array_zeros =np.zeros((3,3))

General Format: np.ones(shape)
Key Notes:
Returns a new array of given shape filled with ones.
shape: Tuple indicating the dimensions of the array.

In [12]:
array_ones =np.ones((2,4))

General Format: np.empty(shape)
Key Notes:
Returns a new array of given shape without initializing entries.
shape: Tuple indicating the dimensions of the array.
Note: The contents are uninitialized and may contain arbitrary data.

In [13]:
array_empty =np.empty((2,2))

**b. Perform reshaping, resizing, and flattening of arrays**



In [14]:

original_array = np.arange(12)



General Format: array.reshape(new_shape)

Key Notes:
Changes the shape of an array without changing its
data.
new_shape: Tuple indicating the desired dimensions.
Total number of elements must remain the same.





In [15]:
reshaped_array = original_array.reshape(3,4)


General Format: np.resize(array, new_shape)
Key Notes:
Returns a new array with the specified shape.
new_shape: Tuple indicating the desired dimensions.
If the new size is larger, the array is repeated to fill the new shape.
If smaller, the array is truncated.


In [16]:
resized_array = np.resize(original_array,(6,2))


General Format: array.flatten()
Key Notes:
Returns a copy of the array collapsed into one dimension.
The result is a new 1D array; original array remains unchanged.

In [17]:
flattened_array = reshaped_array.flatten()

General Format: array[start_row:end_row, start_col:end_col]
Key Notes:

**Slicing Rows:**

1.start_row: Starting index (inclusive).
end_row: Ending index (exclusive).

2.: alone means start or end to the limit of the dimension.

**Slicing Columns:**
1.start_col: Starting index (inclusive).

2.end_col: Ending index (exclusive).

3.Indices are zero-based: The first element has an index of 0.
array[1:, 2:]:


Rows: From index 1 to the end.
Columns: From index 2 to the end

In [24]:
slice_array = reshaped_array[1:,2:]
print(slice_array)

[[ 6  7]
 [10 11]]


**Syntax: bool_mask = array [comparison_operator] value**
Generates a boolean array where each element is True if the condition is met, False otherwise

**Syntax: filtered_array = array[bool_mask]**
 Selects elements from array where the corresponding value in bool_mask is True.

In [34]:
# Creating a boolean mask
array =np.random.randint(low=0,high=100,size=10)
bool_mask = array>50

# Applying the mask to filter the array
filtered_array = array[bool_mask]
print(filtered_array)

[72 72 55 66 61 75 85]
